DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  proficiency VARCHAR(100) NOT NULL,
  ikon BOOLEAN DEFAULT FALSE,
  epic BOOLEAN DEFAULT FALSE,
  indy BOOLEAN DEFAULT FALSE,
  mountain_collective BOOLEAN DEFAULT FALSE
);